version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: 'Dockerfile'
    networks:
      nsfan:
        aliases:
          - frontend
    ports:
      - '8080:80'

networks:
  nsfan:
    name: nsfan
